<?php

namespace ContainerVCznZoA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ROm911iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rOm911i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rOm911i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CompetenceController::delete' => ['privates', '.service_locator.4jAglVv', 'get_ServiceLocator_4jAglVvService', true],
            'App\\Controller\\CompetenceController::edit' => ['privates', '.service_locator.4jAglVv', 'get_ServiceLocator_4jAglVvService', true],
            'App\\Controller\\CompetenceController::index' => ['privates', '.service_locator.mOufrFG', 'get_ServiceLocator_MOufrFGService', true],
            'App\\Controller\\CompetenceController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CompetenceController::show' => ['privates', '.service_locator.9Uxl6IF', 'get_ServiceLocator_9Uxl6IFService', true],
            'App\\Controller\\MetierController::delete' => ['privates', '.service_locator.FKOtdlG', 'get_ServiceLocator_FKOtdlGService', true],
            'App\\Controller\\MetierController::edit' => ['privates', '.service_locator.FKOtdlG', 'get_ServiceLocator_FKOtdlGService', true],
            'App\\Controller\\MetierController::index' => ['privates', '.service_locator.RvAJznU', 'get_ServiceLocator_RvAJznUService', true],
            'App\\Controller\\MetierController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MetierController::show' => ['privates', '.service_locator.mZW_99c', 'get_ServiceLocator_MZW99cService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CompetenceController:delete' => ['privates', '.service_locator.4jAglVv', 'get_ServiceLocator_4jAglVvService', true],
            'App\\Controller\\CompetenceController:edit' => ['privates', '.service_locator.4jAglVv', 'get_ServiceLocator_4jAglVvService', true],
            'App\\Controller\\CompetenceController:index' => ['privates', '.service_locator.mOufrFG', 'get_ServiceLocator_MOufrFGService', true],
            'App\\Controller\\CompetenceController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CompetenceController:show' => ['privates', '.service_locator.9Uxl6IF', 'get_ServiceLocator_9Uxl6IFService', true],
            'App\\Controller\\MetierController:delete' => ['privates', '.service_locator.FKOtdlG', 'get_ServiceLocator_FKOtdlGService', true],
            'App\\Controller\\MetierController:edit' => ['privates', '.service_locator.FKOtdlG', 'get_ServiceLocator_FKOtdlGService', true],
            'App\\Controller\\MetierController:index' => ['privates', '.service_locator.RvAJznU', 'get_ServiceLocator_RvAJznUService', true],
            'App\\Controller\\MetierController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MetierController:show' => ['privates', '.service_locator.mZW_99c', 'get_ServiceLocator_MZW99cService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CompetenceController::delete' => '?',
            'App\\Controller\\CompetenceController::edit' => '?',
            'App\\Controller\\CompetenceController::index' => '?',
            'App\\Controller\\CompetenceController::new' => '?',
            'App\\Controller\\CompetenceController::show' => '?',
            'App\\Controller\\MetierController::delete' => '?',
            'App\\Controller\\MetierController::edit' => '?',
            'App\\Controller\\MetierController::index' => '?',
            'App\\Controller\\MetierController::new' => '?',
            'App\\Controller\\MetierController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CompetenceController:delete' => '?',
            'App\\Controller\\CompetenceController:edit' => '?',
            'App\\Controller\\CompetenceController:index' => '?',
            'App\\Controller\\CompetenceController:new' => '?',
            'App\\Controller\\CompetenceController:show' => '?',
            'App\\Controller\\MetierController:delete' => '?',
            'App\\Controller\\MetierController:edit' => '?',
            'App\\Controller\\MetierController:index' => '?',
            'App\\Controller\\MetierController:new' => '?',
            'App\\Controller\\MetierController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
